/*1.TẠO  TRIGGER  ĐỂ CẬP  NHẬT  THÔNG  TIN  TRIGIA  TRONG  BẢNG  HOADON  TỪ VIỆC  TÍNH  TOÁN SL*GIA CỦA TỪNG MÃ SẢN PHẨM, 
ÁP DỤNG CHO 3 KIỂU THAY ĐỔI DỮ LIỆU LÀ INSERT, UPDATE, DELETETABLE: [CTHD], [HOADON], [SANPHAM]
2.TẠO TRIGGER THÔNG BÁO NẾU SỐLƯỢNG HÀNG TỒN KHO CỦA MASP <= 10
TRONG TRƯỜNG  HỢP  XUẤT  HÀNG  >  SL  TỒN  KHO ->  HIỂN  THỊ THÔNG  BÁO  VỀ SLSP  CẦN  NHẬP THÊM VÀ NUOCSX MASP ĐÓ
.TABLE: [CTHD], [WAREHOUSE_REMAINING]SELECT DISTINCT MASP,50 AS QUANTITY INTO WAREHOUSE_REMAINING FROM CTHD 
VÍ DỤ:‘MÃ SẢN PHẨM BB01 HIỆN CHỈ CÒN 6 SẢN PHẨM’‘CẦN NHẬP THÊM 5 SẢN PHẨM MÃ BB02 TỪ TRUNG QUỐC’
3.TẠO TRIGGER  CẬP  NHẬT DỮLIỆU  WAREHOUSE  KHI MÀ  THÔNG TIN  HỢP ĐỒNG ĐƯỢC CẬP  NHẬT VÀO TRONG CTHD
----TẠO BẢNG HÀNG TỒN KHO(WAREHOUSE): SELECT DISTINCT MASP,50 AS QUANTITY INTO WAREHOUSE_REMAINING FROM CTHD*/
select * from HOADON

--1
alter trigger TRG_SANPHAM
on SANPHAM
for update
as
begin
	declare cur cursor for 
	select CTHD.SOHD, GIA, SL from (inserted inner join CTHD on inserted.MASP = CTHD.MASP
	inner join HOADON on HOADON.SOHD = CTHD.SOHD)
	open cur

	declare @GIA int, @SOHD int, @SL int
	FETCH next from cur into @SOHD, @GIA, @SL

	while @@FETCH_STATUS=0
		begin
			update HOADON set TRIGIA = @GIA * @SL
			where HOADON.SOHD = @SOHD
			FETCH next from cur into @SOHD, @GIA, @SL
		end
	close cur
	deallocate cur
end

alter trigger TRG_CTHD
on CTHD
for update
as
begin
	declare cur cursor for 
	select inserted.SOHD, SANPHAM.GIA, inserted.SL from (inserted inner join SANPHAM on inserted.MASP = SANPHAM.MASP
	inner join HOADON on HOADON.SOHD = inserted.SOHD)
	open cur

	declare @GIA int, @SOHD int, @SL int
	FETCH next from cur into @SOHD, @GIA, @SL

	while @@FETCH_STATUS=0
		begin
			update HOADON set TRIGIA = @GIA * @SL
			where HOADON.SOHD = @SOHD
			FETCH next from cur into @SOHD, @GIA, @SL
		end
	close cur
	deallocate cur
end


begin transaction
rollback transaction

-- Câu 2
drop table WAREHOUSE_REMAINING
SELECT DISTINCT MASP,50 AS QUANTITY INTO WAREHOUSE_REMAINING FROM CTHD

alter trigger TRG_Check_Sl
on CTHD
for insert
as
begin
			DECLARE CUR CURSOR FOR
			SELECT MASP, SL FROM INSERTED
			OPEN CUR

			DECLARE @MASP NVARCHAR(MAX), @SL INT
			FETCH NEXT FROM CUR INTO @MASP, @SL

			WHILE @@FETCH_STATUS = 0
			BEGIN				
				declare @QUANTITY int = (select QUANTITY from WAREHOUSE_REMAINING where MASP = @MASP)
				declare @NUOCSX nvarchar(max) = (select NUOCSX from SANPHAM where MASP = @MASP)
					if @SL > @QUANTITY
						begin						
						print N'CẦN NHẬP THÊM' + str(@SL - @QUANTITY) + N' SẢN PHẨM MÃ ' + @MASP + N' TỪ ' + @NUOCSX
						FETCH NEXT FROM CUR INTO @MASP, @SL
						continue;
						end
					else
						begin						
						UPDATE WAREHOUSE_REMAINING
						SET QUANTITY = QUANTITY - @SL
						WHERE MASP = @MASP
						declare @QUANTITY_2 int = (select QUANTITY from WAREHOUSE_REMAINING where MASP = @MASP)
						if  @QUANTITY_2  < 10
							print N'MÃ SẢN PHẨM ' + @MASP + N' HIỆN CHỈ CÒN' + str(@QUANTITY_2) + N' SẢN PHẨM'
						
						FETCH NEXT FROM CUR INTO @MASP, @SL
						end
			END
			CLOSE CUR
			DEALLOCATE CUR
end

-- Câu 3
--- INSERT INTO CTHD -> TRỪ ĐI SLSP MASP TƯƠNG ỨNG TRONG BẢNG WAREHOUSE_REMAINING
CREATE TRIGGER TRG_CTHD_INSERT
ON CTHD
FOR INSERT
AS
BEGIN
	DECLARE CUR CURSOR FOR
		SELECT MASP, SL FROM INSERTED
	OPEN CUR

	DECLARE @MASP NVARCHAR(MAX), @SL INT
	FETCH NEXT FROM CUR INTO @MASP, @SL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE WAREHOUSE_REMAINING
		SET QUANTITY = QUANTITY - @SL
		WHERE MASP = @MASP
		FETCH NEXT FROM CUR INTO @MASP, @SL
	END
	CLOSE CUR
	DEALLOCATE CUR
END

--- DELETE FROM CTHD -> CỘNG THÊM SLSP MASP TƯƠNG ỨNG TRONG BẢNG WAREHOUSE_REMAINING
alter TRIGGER TRG_CTHD_DELETE
ON CTHD
FOR Delete
AS
BEGIN
	DECLARE CUR CURSOR FOR
		SELECT MASP, SL FROM DELETED
	OPEN CUR

	DECLARE @MASP NVARCHAR(MAX), @SL INT
	FETCH NEXT FROM CUR INTO @MASP, @SL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE WAREHOUSE_REMAINING
		SET QUANTITY = QUANTITY + @SL
		WHERE MASP = @MASP
		FETCH NEXT FROM CUR INTO @MASP, @SL
	END
	CLOSE CUR
	DEALLOCATE CUR
END
--- UPDATE CTHD -> TRỪ ĐI SLSP MASP ĐƯỢC THAY THẾ, CỘNG THÊM SLSP MASP BỊ THAY THẾ TRONG BẢNG WAREHOUSE_REMAINING
CReate TRIGGER TRG_CTHD_UPDATE
ON CTHD
FOR Update
AS
BEGIN
	DECLARE CUR CURSOR FOR
		SELECT MASP, SL FROM INSERTED
		UNION ALL
		SELECT MASP, -1*SL FROM DELETED
	OPEN CUR

	DECLARE @MASP NVARCHAR(MAX), @SL INT
	FETCH NEXT FROM CUR INTO @MASP, @SL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		UPDATE WAREHOUSE_REMAINING
		SET QUANTITY = QUANTITY - @SL
		WHERE MASP = @MASP
		FETCH NEXT FROM CUR INTO @MASP, @SL
	END
	CLOSE CUR
	DEALLOCATE CUR
END